### ISSUE TITLE
Create some text around the wireless case, where devices have to bring down their tranceivers to save power

### ISSUE THREAD

**Issue by elear** [anima-wg/anima-brski-prm#10]
See PR #9 for text.

**Comment by stfries** [comment]
Was included as limitation section. General boundary conditions may also be discussed in architecture documents. Eliot already contacted Brendan Moran to include specifics into Draft ["A summary of security-enabling technologies for IoT devices" ](https://datatracker.ietf.org/doc/draft-moran-iot-nets/)
