### ISSUE TITLE
interruption in the process to supply resp. objects - how does it restart ?

### ISSUE THREAD

**Issue by siethower** [anima-wg/anima-brski-prm#101]
Comment from Toerless to section 6.3

> [major]
 
> What happens if there is an interruption in the process, and the registrar-agent
> does not get to record on disk the successful enrolment ? how does it restart ?
> It could attempt to re-send the same voucher, but then it should also get
> again success status instead of some errror it can't interpret "you already
> gave me the voucher 5 minutes ago".
 
> Aka: would be good to ensure that the sending of voucher and status can repeated
> an result in the same positive status.
 
> 2086    6.3.3.  Pledge: Wrapped-CA-Certificate(s) Processing

**Comment by stfries** [comment]
Would it be sufficient to provide a reference to section 6.4 querying the pledge status in general and then jump back to the state-machine were the pledge-agent stopped?

**Comment by stfries** [comment]
Included statement that the registrar-agent may query the status explicitly when not receiving voucher telemetry information from the pledge and may re-sent the voucher.
