### ISSUE TITLE
"Representation of pledge enroll status telemetry" add negative example

### ISSUE THREAD

**Issue by siethower** [anima-wg/anima-brski-prm#105]
Comment from Toerless to section 6.3

> 2177            Figure 16: Representation of pledge enroll status telemetry
>  
> negative example (only payload) would again be a fine addition.

**Comment by stfries** [comment]
Proposal to add:
# Example: Decoded payload "pledge-enroll-status" representation
  in JSON syntax
{
  "version": 1,
  "status": false,
  "reason": "Enrollment response could not be verified",
  "reason-context": {
    "additional": "no matching trust anchor"
  }
}

**Comment by stfries** [comment]
Included example
