### ISSUE TITLE
"registrar-agent signatures" check consistent use

### ISSUE THREAD

**Issue by siethower** [anima-wg/anima-brski-prm#106]
Comment from Toerless to section 6.3

> 2221       Section 6.2.
>  
> 2223       The registrar-agent sends the pledge voucher status without
> 2224       modification to the registrar with an HTTP-over-TLS POST using the
> 2225       registrar endpoint "/.well-known/brski/voucher_status".  The Content-
> 2226       Type header is kept as application/jose+json as described in
> 2227       Figure 14 and depicted in the example in Figure 15.
>  
> [major]
>  
> So, in the first part of the review i was trying to suggest positive spin text
> around all the complexity of introducing registar-agent authentication in
> some messages, such as being able to track on the registrar and the backend
> behind it, who (which registstrar-agent) was assisting he enrollment and
> hence also likely co-checks for the pledge.
>  
> But when you simply pass through the telementry without including an
> identity of the registar-agent, then this benefit goes out the door, and
> we could rather remove all other registrar-agent signatures from the spec
> because they serve no purpose other than to track somewhere who was
> sending messages back and forth between pledge and registrar.
>  
> Aka: either have a scheme where all the steps taken can be traced back to
> a registrar-agent (aka: put the plege-responses into a registrar-agent
> signed container), or get rid of all the then unnecessary registrar-agent
> signatures...

**Comment by stfries** [comment]
Point for discussion. The onboarding of new devices seems like a sensitive action, in which an audit trail of the involved entities can be provided as it involved the trust handover. The telemetry is assumed to be much less critical.

**Comment by stfries** [comment]
Some additional thoughts: 
- The registrar knows the interacting registrar-agent from the authentication of the registrar-agent towards the registrar using LDevID (RegAgt) and can log it accordingly
- The telemetry information from the pledge can be correlated to the voucher response provided from the registrar to the registrar-agent and further to the pledge. 
- The telemetry information, when provided to the registrar is provided via the registrar-agent. 
This should avoid the additional information, as the registrar can track, which registrar-agent has provided the telemetry information.

**Comment by toerless** [comment]
The aditional thoughts look good. It would be useful to have some paragraph stating them and saying "The registrar SHOULD log the transaction provided for a pledge via registrar-agent and include the identity of the registrar-agent in these logs."

... followed by the three bullet points from "additional thoughts".
