### ISSUE TITLE
certificate revokation by registrar, in case of failure

### ISSUE THREAD

**Issue by siethower** [anima-wg/anima-brski-prm#107]
Comment from Toerless to section 6.3

> 2268       status codes as defined by the HTTP standard.  Based on the failure
> 2269       case the registrar MAY decide that for security reasons the pledge is
> 2270       not allowed to reside in the domain.  In this case the registrar MUST
> 2271       revoke the certificate.  The registrar-agent may use the response to
> 2272       signal success / failure to the service technician operating the
> 2273       registrar agent.  Within the server log the registrar SHOULD capture
> 2274       this telemetry information.
>  
> [major]
>  
> This part (2268-2274) seems to be new compared to rfc8995. If there is a reference
> to this revocation after enrolment in rfc8995, please add. Otherwise it would
> be great to add an example. For example, if the pledge failed to install the
> certificate because of clock messup, this does not mean that the registrar
> MUST revoke the certificate. it could as well end up for the technician
> having to replace NVram battery on the pledge or the like and re-send the
> voucher/certificate to the pledge.
>  
> Aka: i fail to come up with an idea for the decision for the pledge not being
> allowed to reside in the domain after the registrar did previously happily
> provde a cert to the registrar-agent for the pledge.
>  
>  
> 2276    6.4.  Request Pledge-Status by Registrar-Agent from Pledge

**Comment by stfries** [comment]
Proposal to add an example:

"An example case for the registrar revoking the issued LDevID for the pledge is when the pledge was not able to verify the received LDevID certificate and therefore did send a 406 (Not Acceptable) response. In this case the registrar may revoke the LDevID certificate as the pledge did no accepted it for installation."

**Comment by stfries** [comment]
Included proposal
