### ISSUE TITLE
"Pledge-Status - Trigger"  - Naming

### ISSUE THREAD

**Issue by siethower** [anima-wg/anima-brski-prm#108]
Comment from Toerless to section 6.4

> 2307    6.4.1.  Pledge-Status - Trigger (Registrar-Agent to Pledge)
>  
> I don't think "trigger" is a good name here. It made sense when the
> reply are "requests", but in this case it should be called (IMHO) a Pledge Status Request,
> because it's answered by a response.

**Comment by stfries** [comment]
Agreed. As the text in the section also states response and not trigger, we should consequently rename the heading to Pledge-Status Request.

Proposal to close once incorporated.

**Comment by stfries** [comment]
incorporated as proposed
