### ISSUE TITLE
replicated text from RFC8995 for status information?

### ISSUE THREAD

**Issue by siethower** [anima-wg/anima-brski-prm#109]
Comment from Toerless to section 6.4

> 2309       The registrar-agent requests the pledge-status via HTTP POST on the
> 2310       defined pledge endpoint: "/.well-known/brski/ps"
>  
> 2312       The registrar-agent Content-Type header for the pledge-status request
> 2313       is: application/jose+json.  It contains information on the requested
> 2314       status-type, the time and date the request is created, and the
> 2315       product serial-number of the pledge contacted as shown in Figure 19.
> 2316       The pledge-status request is signed by registrar-agent using the
> 2317       LDevID(RegAgt) credential.
>  
> 2319       The following Concise Data Definition Language (CDDL) [RFC8610]
> 2320       explains the structure of the format for the pledge-status request.
> 2321       It is defined following the status telemetry definitions in BRSKI
> 2322       [RFC8995].  Consequently, format and semantics of pledge-status
> 2323       requests below are for version 1.  The version field is included to
> 2324       permit significant changes to the pledge-status request and response
> 2325       in the future.  A pledge or a registrar-agent that receives a pledge-
> 2326       status request with a version larger than it knows about SHOULD log
> 2327       the contents and alert a human.
>  
> Seems like a lot of replicated text from RFC8995. See if you can cut it down
> to just reference and whatever is new here.

**Comment by stfries** [comment]
The CDDL used is not quite the same as in BRSKI as it contains the status type and also time/date information. Moreover, as the communication is done using self-contained objects, the request and response messages are signed. 

Proposal to leave the text and close the issue.

**Comment by stfries** [comment]
closed as of reasoning above. We have separate issue for the usage of CDDL in general
