### ISSUE TITLE
"Figure 22: Example of pledge-status response" - example text

### ISSUE THREAD

**Issue by siethower** [anima-wg/anima-brski-prm#112]
Comment from Toerless to section 6.4

> 2483       # Decoded payload "status-response" representation in JSON syntax
> 2484       {
> 2485         "version": 1,
> 2486         "status": "enroll-success",
> 2487         "reason-context": {
> 2488           "additional" : "JSON"
>  
> s/JSON/example text/ ??
>  
> 2489         }
> 2490       }

**Comment by stfries** [comment]
Include example in the figure

**Comment by stfries** [comment]
included as proposed
