### ISSUE TITLE
status reply for "factory-default"

### ISSUE THREAD

**Issue by siethower** [anima-wg/anima-brski-prm#113]
Comment from Toerless to section 6.4

> 2502                    Figure 22: Example of pledge-status response
>  
> 2504       In case "factory-default" the pledge does not possess the domain
> 2505       certificate resp. the domain trust-anchor.  It will not be able to
> 2506       verify the signature of the registrar-agent in the bootstrapping-
> 2507       status request.
>  
> and.... just provide the status reply without authentication ?!

**Comment by stfries** [comment]
Proposal to include for case factory default: 
"The pledge MAY respond with the information about the factory-default state"

**Comment by stfries** [comment]
included enhanced information: 

  The pledge MAY respond with the information about the factory-default state as it may not be able to  verify the request message from a registrar-agent due to a missing domain certificate.
