### ISSUE TITLE
"raises the question why we're not using https between pledge and registrar-agent" - in Privacy Considerations

### ISSUE THREAD

**Issue by siethower** [anima-wg/anima-brski-prm#114]
Comment from Toerless to section 9

> 2757       The communication between the pledge and the registrar-agent is
> 2758       performed over plain HTTP.  Therefore, it is subject to disclosure by
> 2759       a Dolev-Yao attacker (an "oppressive observer")[onpath].  Depending
> 2760       on the requests and responses, the following information is
> 2761       disclosed.
>  
> This of course raises the question why we're not using https between pledge
> and registrar-agent to prohibit such mitm obervation (beyond other good reasons
> to use https that i brought up in my first part of the review).
>  
> Remember that the registrar can always authenticate the IDevID of pledges,
> so arguably the pledge vendors trust anchors can also be provisionined
> onto registrar-agents (not more difficult than the serial numbers that you
> assume to be provisionalbe - which i find much more difficult), and the
> pledge simply does not even need to do any registrar-agent certificate
> verification, but solely because of TLS PFS, this one-side verification
> should suffice to prohibit passive observation.

**Comment by stfries** [comment]
As we have meanwhile added optional TLS support for the communication between the pledge and the pledge-agent in section 6.1 and Appendix B and mentioned this option in the privacy considerations.

This issue can be closed.
