### ISSUE TITLE
Privacy Considerations - complete?

### ISSUE THREAD

**Issue by siethower** [anima-wg/anima-brski-prm#115]
Comment from Toerless to section 9

> 2774       *  the Timestamp data could reveal the activation time of the device.
>  
> 2776       *  the Status data of the device could reveal information about the
> 2777          current state of the device in the domain network.
>  
> I'll comment on whether this is complete after we have (hopefully not)
> concluded that we cannot/should-not use http.
>  
> 2779    10.  Security Considerations

**Comment by stfries** [comment]
As we meanwhile also support TLS (optionally) between the pledge and the registrar agent, this issue may be closed.
