### ISSUE TITLE
use of www.example.com in pledge URL

### ISSUE THREAD

**Issue by mcr** [anima-wg/anima-brski-prm#120]
> The URI path begins with "http://www.example.com/.well-known/brski" followed by a path-suffix that indicates the intended operation.

First, if we have to put a hostname here, then maybe we should put http://pledge.example/
but perhaps the bigger point which I'm looking for text about is that actually the Host: header needs to

a. be empty, not included by Registrar-Agent
b. or be the IP address of the pledge
c. in any case, ignored by the pledge.

https://httpd.apache.org/docs/current/vhosts/ is a bit relevant, in that it describes how to do IP and Name Based virtual hosting, and the pledge needs definitely not do Name-Based.

**Comment by stfries** [comment]
- if host header is included, pledge has to ignore it. 
- server shall except any host header
Add sentence that the pledge has to accept all host headers. Include reference to RFC 9110
