### ISSUE TITLE
we lost the agent-signed-data

### ISSUE THREAD

**Issue by mcr** [anima-wg/anima-brski-prm#122]
> The body of the agent-signed-data contains an "ietf-voucher-request:agent-signed-data" element (defined in {{I-D.ietf-anima-rfc8366bis}}):

But, rfc8366bis does not have such a thing.
It seems that we lost it.  Is it really a voucher?

**Comment by stfries** [comment]
Not sure I understand. We had the agent-signed data defined in the voucher request to ensure a pledge was contacted by a specific registrar-agent. That data is not in the voucher itself, but in the voucher-request, which uses the voucher YANG.
In the bis it is defined in [section 7.1](https://www.ietf.org/archive/id/draft-ietf-anima-rfc8366bis-07.html#name-tree-diagram-4) and also in [section 7.2](https://www.ietf.org/archive/id/draft-ietf-anima-rfc8366bis-07.html#name-ietf-voucher-request-module-2). What are we missing?

**Comment by stfries** [comment]
Michael, not sure if that was a misreading of agent-signed data use in the pledge-voucher-request and the second signature of the voucher by the registrar. Where did you see a problem?

**Comment by stfries** [comment]
Ensure that the provisioning of the registrar agent with the serial number information is contained in the draft. It is stated in the discovery section that the registrar-agent has the serial numbers pre-provisioned or may query available pledges.
Double check

**Comment by stfries** [comment]
The statement can be found in the preconditions for the registrar-agent in [section 6.1 ](https://www.ietf.org/archive/id/draft-ietf-anima-brski-prm-09.html#name-request-objects-acquisition) of BRSKI-PRM

Proposal to close the issue
