### ISSUE TITLE
"domain/site" terminology definition and consistent usage

### ISSUE THREAD

**Issue by mkovatsc** [anima-wg/anima-brski-prm#128]
The document uses site and domain an various combinations, but never clearly defines these terms.

RFC8995 defines:

> Domain: The set of entities that share a common local trust anchor. This includes the proxy, registrar, domain CA, management components, and any existing entity that is already a member of the domain.

This does not clearly differentiate from the manufacturer domain, which also exists.

Proposal is to take the definition from RFC8995, but clarify the difference, e.g.:

* ... customer or operational domain similar to the locally-significant domain? ... 802.1AR (to be improved).
* consistently use "domain" to match with "domain registrar"

**Comment by stfries** [comment]
Has been address in the [latest commit](https://github.com/anima-wg/anima-brski-prm/commit/f3f21c6f9eff216984adb3587cfa5efc31315d79). We utilize the term domain as in BRSKI and stated in the terminology section, that the term site may be used anonymously. The term site is not used stand alone anymore, rather to refer to a specific customer installation.

----

may be closed

**Comment by stfries** [comment]
- remove "site" from terminology as describing it equivalent to"domain"
- provide explanation or figure to show nomadic connectivity of registrar-agent
- Toerless to sketch a figure

**Comment by stfries** [comment]
Added the following description to the registrar-agent  to the explanation of Figure 1 in[ section 5](https://www.ietf.org/archive/id/draft-ietf-anima-brski-prm-10.html#name-architectural-overview)
  The registrar-agent may be realized as stand-alone component supporting nomadic activities of a service technician moving between different installation sites. 
  Contrary, the registrar-agent may also be realized as co-located functionality for a registrar, to support pledges in pledge-responder-mode.

**Comment by stfries** [comment]
Included proposed text from PR https://github.com/anima-wg/anima-brski-prm/pull/131 for separate sections on nomadic connectivity of a registrar-agent and an integrated registrar-agent into the domain registrar. This enhances the already incorporated text from issue https://github.com/anima-wg/anima-brski-prm/issues/128.

only deleted the additional note in the section with integrated registrar-agent, as the term BRSKI proxy is not defined and we did not want t introduce a new term.

Changes are provided in commit [285f3f2](https://github.com/anima-wg/anima-brski-prm/commit/285f3f2651024fa3342b7a49bf38cb633b78d11f)

------

can be closed

**Comment by mkovatsc** [comment]
My comments were addressed well:

* site versus domain is fixed with consistent "domain" usage
* aspects connected to "site" are now stated explicitly
