### ISSUE TITLE
Problem in BRSKI (also AE/PRM) through missing voucher check by registrar before forwarding voucher to pledge?

### ISSUE THREAD

**Issue by stfries** [anima-wg/anima-brski-prm#13]
During the discussion of multiple signature support for JWS objects, we stumbled upon the following scenario, which may pose a problem:

Assumed components: Access control to Smart Home or Hotel
- Pledge = Smart door lock, 
  - communicates with registrar for bootstrapping
  - has Bluetooth interface for receiving access tokens, e.g., signed from an access control component, which may also reside on the registrar the regular.
- Registrar = Home controller or Building Automation Controller
- MASA = Manufacturer of smart door lock device 								 

Assumed scenario:
- Smart door lock onboards to the new domain and receives a voucher containing two 
root of trust certificates (the second one as rogue certificate, introduced, e.g. by a 
disgruntled employee)
- Smart door lock is expected to provide services in terms of receiving access tokens to e.g., open the door based on the received access token

Normal operation
- Visitor/owner requests access token from Home/Building Controller 
- Access token is a signed object, which has a validity and maybe further information 
and is signed by a credential from the domain (Smart Home or Hotel), which can be 
verified by the smart door lock using the installed (regular) trust anchor	
- Access token is provided via Bluetooth and the smart door lock is the server component  
  
Misuse by an attacker
-	Assumption: attacker possesses the private key to the second trust anchor submitted 
to the smart door lock during onboarding.
-	Attacker issues access token and is able to access the smart home or hotel room
  
Problem 
-	Registrar does not mandatory verify the content of the voucher 

Solution 
-	Registrar validates the voucher according to contained components and rejects (e.g., via audit log request) or drops the voucher if unexpected or non-interpretable information is contained.

Attached is a slide, which explains it also graphically.

[problem.pptx](https://github.com/anima-wg/anima-brski-prm/files/7815839/problem.pptx)

We should discuss this issue in the next design team meeting

**Comment by mcr** [comment]
>   * has Bluetooth interface for receiving access tokens, e.g., signed from an access control component, which may also reside on the registrar the regular.

please explain more?

> * Smart door lock onboards to the new domain and receives a voucher containing two
>   root of trust certificates (the second one as rogue certificate, introduced, e.g. by a
>   disgruntled employee)

How did this occur?   How would a voucher contain this extra root of trust?
Doesn't that imply that the Registrar has been compromised?

**Comment by stfries** [comment]
- Smart door locks are available, e.g., for home owners or hotels. If they use access tokens which are signed an attacker may fake the access token as long as he possesses the private key to the trust anchor previously installed on the pledge.
- As the voucher is extensible, it can be enhanced and may transport more than one trust anchor (see also [BRSKI, section 7.4.3](https://datatracker.ietf.org/doc/html/rfc8995#section-7.4.3). In this case the MASA would have been compromised. 

There are different ways of installing further trust anchors on a pledge I guess. I would just like to avoid that this can already be done without the registrars approval.

**Comment by siethower** [comment]
See https://github.com/anima-wg/anima-jws-voucher/issues/5 , in case of additional signature on Voucher by Registrar is desired.

**Comment by stfries** [comment]
After discussion in ANIMA design team, the attack is not as trivial. The voucher currently supports only one signature out of the box. That means an an attacker would not only have to manipulate the MASA to include two trust anchors, but to also ensure the pledge implements the necessary capability to extract two trust anchors out of the voucher. In this case it may be easier to put the rough trust anchor into the FW directly.

Contrary it may be used as a feature to allow the registrar to provide two trust anchors in the registrar voucher request to let the MASA include both into the issued voucher. But this also requires definition of additional functionality and enhancements to the voucher. 

may be closed
