### ISSUE TITLE
how do we communicate number of CSRs to be collected?

### ISSUE THREAD

**Issue by mcr** [anima-wg/anima-brski-prm#14]
The pledge may have some policy about how many application certificates it needs.
The registrar-agent may also have some policy about how many application certificates it expects to collect from the pledge.

We need to write this down, and we need to determine how to signal situations where the two expectations are not consistent, or not met.  The pledge may have functionality which is not being used in a particular deployment.  On the other hand, the registrar-agent may need to signal to the installer if it can't get some specific application CSR.

**Comment by stfries** [comment]
Just reviewed existing issues we already discussed. In issues #7 and #8  we already discussed the necessity of supporting multiple CSRs and also multiple certificates in the enrollment response. The result was to concentrate with BRSKI-PRM on the generic-LDevID. The provided endpoints may be used for further enrollment requests.

**Comment by mcr** [comment]
The deployment of additional (application) LDevID will occur after onboarding has completed.  The LDevID will provide for network access, at which point the device can use push, pull or configuration mechanisms to acquire application specific certificates.
