### ISSUE TITLE
Clarify terminology of "endpoint"

### ISSUE THREAD

**Issue by stfries** [anima-wg/anima-brski-prm#16]
(based on feedback from Esko) 

- Term "endpoint" could be confusing 

Proposal: The term endpoint used in the context of this document is similar to resources in CoAP and also in HTTP (RFC 9110). Endpoints are accessible via .well-known URIs.

**Comment by EskoDijk** [comment]
I did some further study on the terminology of "endpoint" and it comes from the web services world. There an "endpoint" is associated to a URL that a client can use to gain access to a particular web application/service.

The web services can be considered at different granularity of course, so for one developer these may be 2 separate endpoints:
* my.example.com/shop/buyBooks
* my.example.com/shop/buyShirts

while for another developer it may be a single endpoint
* my.example.com/shop
which has multiple resources underneath.

So it depends on viewpoint and on the way of access( e.g. does the client intially go to /shop, or directly goes to either one of /shop/buyBooks or shop/buyShirts ?  In the latter case there's a higher chance of considering it as 2 endpoints. )

So for draft-PRM we may consider /.well-known/brski as a single endpoint, or we may consider each resource underneath /.well-known/brski as an endpoint.  The latter seems more conforming to web services language.

However, we have to note that HTTP/CoAP don't use "endpoint" but "resource" in this way so conforming to IETF terminology might be more important than conforming to the web services industry terms. Up for discussion :)

**Comment by stfries** [comment]
Based on the approach in RFC 8995 I would propose to use endpoint in BRSKI-PRM in the context of each resource available under /.well-known/brski to use it consistently. This would align with the current use of HTTP in the draft. In addition I would propose to state an explanatory sentence like "The term endpoint used in the context of this document is similar to resources in CoAP and also in HTTP (RFC 9110). It is not used to describe a device. Endpoints are accessible via .well-known URIs.", to make clear that for CoAP it would relate to resources.

**Comment by EskoDijk** [comment]
Ok for me.

**Comment by stfries** [comment]
Done
