### ISSUE TITLE
Separation of voucher-request trigger and enrollment request trigger

### ISSUE THREAD

**Issue by stfries** [anima-wg/anima-brski-prm#17]
(based on feedback from Esko) 

There may be use cases, in which the registrar agent only requests the pledge-voucher-request to allow to transmit vendor specific information (like licenses). This information can then be considered in the pledge-enrollment-request, which will be requested in a separate pledge-enrollment-request trigger.

Proposal to insert a note to optionally allow the separation of the trigger for pledge-voucher-request and pledge-enrollment-request. It would be up to the registrar-agent to ask for one or both.

**Comment by siethower** [comment]
As discussed having this note is fine.  
Please include.

**Comment by stfries** [comment]
Included the following text:

Note that the registrar-agent may trigger the pledge for the PVR or the PER or both. It is expected that this will be aligned with a service technician workflow doing the pledge installation.
