### ISSUE TITLE
Clarify supported environments and application examples in section 3

### ISSUE THREAD

**Issue by stfries** [anima-wg/anima-brski-prm#19]
(based on comments by Esko)

Sections 3.x there is “Supported Environment” and there is “Application Examples”. This distinction is not clear. 

Proposal: Make the section supported environments as introduction to describe it from a general point of view and keep the application examples as more specific description.

**Comment by stfries** [comment]
Combined 3.1 and 3.2 to "Supported Environments and Use Case Examples"

BRSKI-PRM is applicable in environments in which pledges may have different technology stacks or pledges may have no direct connection to the domain registrar, but are expected to be managed by the same registrar.
This can be motivated by pledges deployed in networks not connected to the operational customer site/domain, e.g., during construction of a site. 
Another environment relates to the assembly of cabinets, which are prepared to be installed on a customer site/domain. 
As there is no direct connection to the registrar available in these environments the solution specified allows the pledges to act in a server role so that they can be accessed by a commissioning tool to trigger the bootstrapping. As BRSKI focuses on the pledge in a client role, initiating the bootstrapping, BRSKI-PRM defines pledges acting as a server answering to requests for pledge-voucher-request (PVR) objects and pledge-enrollment-request (PER) objects and cunsumption of the responses.  

The following industrial examples motivate support of BRSKI-PRM to support pledges acting as server as well as pledges with limited connectivity to the registrar.

**Comment by mcr** [comment]
The situation of cabinets being assembled, and the pledges being BMCs of servers is a really important use case I hadn't thought about.

**Comment by siethower** [comment]
Some rewriting of chapter: "Supported Environments and Use Case Examples"  

BRSKI-PRM is applicable to environments where pledges may have different behaviour: pledge-responder-mode, or pledges may have no direct connection to the domain registrar. Either way pledges are expected to be managed by the same registrar.
This can be motivated by pledges deployed in environments not yet connected to the operational customer site/domain network, e.g., at construction time. 
Another environment relates to the assembly of cabinets, which are prepared in advance to be installed on a customer site/domain. 
As there is no direct connection to the registrar available in these environments the solution specified allows the pledges to act in a server role so they can be triggeered for bootstrapping e.g., by a commissioning tool. As BRSKI focuses on the pledge in a client role, initiating the bootstrapping (pledge-initiator-mode), BRSKI-PRM defines pledges acting as a server (pledge-responder-mode) responding to requests for PVR and PER objects and consumption of the result objects.  

The following examples motivate support of BRSKI-PRM to support pledges acting as server as well as pledges with limited connectivity to the registrar.

**Comment by stfries** [comment]
Included as proposed
