### ISSUE TITLE
Check text for repetitions of information

### ISSUE THREAD

**Issue by EskoDijk** [anima-wg/anima-brski-prm#22]
Some information is repeated across multiple sections, or repeated within the same section. An effort could be done to make the text more compact.

One idea is to make more use of abbreviations so instead of repeating multiple times
"registrar voucher request (RVR)"

we could write just "RVR" in most cases. The term can be introduced in the terminology section.
Same for PVR, RER, PRM, ...

**Comment by stfries** [comment]
Good idea with the abbreviation, this will already reduce the text.
If you stumble upon specific repetitions, just provide a pointer to the corresponding section. That will make it easier to identify.

**Comment by stfries** [comment]
done
