### ISSUE TITLE
Mention in scope section (3.*) that BRSKI and BRSKI-PRM can be used together

### ISSUE THREAD

**Issue by EskoDijk** [anima-wg/anima-brski-prm#24]
Proposal is to mention in the scope section 3.* somewhere that BRSKI can be used together with BRSKI-PRM in one Pledge.

For example  a product could have:
* Pledge is powered on and actively tries to perform BRSKI  - attempting to discover a Join Proxy.
* If this doesnt work, it may stop that discovery and wait for a Registrar-Agent to contact it for BRSKI-PRM.
* If after some waiting time still nothing happened, it may move back to step 1.
* If during the active BRSKI phase (discovering a Join Proxy) a Registrar-Agent shows up, that will work too.

**Comment by stfries** [comment]
Good idea, added to section 3: 

While BRSKI-PRM defines support for pledges in responder mode, there may be pledges, which can act in both modes, initiator and responder. 
In these cases BRSKI-PRM can be combined with BRSKI as defined in {{RFC8995}} or BRSKI-AE {{I-D.ietf-anima-brski-ae}} to allow for more bootstrapping flexibility.
