### ISSUE TITLE
Unify terminology of "enrollment object", "certification object", "enrollment request object", etc.

### ISSUE THREAD

**Issue by EskoDijk** [anima-wg/anima-brski-prm#27]
There's different terms being used ; preferably a smaller set is selected and also defined in the Terminology section.

Current use:
> pledge-enrollment-request object
> enrollment object
> certification object
> certification request object
> enrollment request object
> (maybe more)

Proposed:
enrollment object = authenticated self-contained object with data associated to the pledge enrollment procedure
enrollment request object = enrollment object signed by the pledge that requests to enroll in a domain
enrollment response object = enrollment object signed by the registrar that contains a response to an enrollment request

**Comment by stfries** [comment]
I took over explanation into the terminology for PER, PVR, RER and RVR. 
In the more general places "enrollment objects" were used to summarize the enrollment objects that are processed by the pledge and the registrar. 

Further discussion on simplification needed.

**Comment by stfries** [comment]
Reworked terminology of "object" usage throughout the document. Used PER and RER whenever possible. Explained that certification request is contained in PER and RER.

Can be closed.

**Comment by siethower** [comment]
Fine for me.  
@EskoDijk please have a look.

**Comment by EskoDijk** [comment]
Agreed! There are a few mentions of "request objects" but I think this is ok, the text explains it, and that covers all the types of request objects.
