### ISSUE TITLE
Unclear sentence " Note that it may be .. if not configured." 5.1

### ISSUE THREAD

**Issue by EskoDijk** [anima-wg/anima-brski-prm#30]
>  Note that it may be used by the registrar-agent instead of the pledge to find the registrar, if not configured.

I'm not sure what was intended here. Perhaps like this:

>  Note that a registrar-agent may use a join proxy to facilitate the TLS connection to the registrar, in the same way that a BRSKI pledge would use a join proxy. This is useful in cases where the registrar-agent does not have full IP connectivity via the domain network, or cases where it has no other means to locate the registrar on the network.

**Comment by stfries** [comment]
took the suggested text into the draft
