### ISSUE TITLE
Use cases where network connectivity gets added at a later time - can device use it?

### ISSUE THREAD

**Issue by EskoDijk** [anima-wg/anima-brski-prm#31]
BRSKI-PRM was designed to cope with initial enrollment, where no network coverage may be available to the pledge(s).

But what if the pledge device gets enrolled using BRSKI-PRM, and then 2 months later the domain/building network is completed. The device can now use its LDevID to fully connect to the domain network and e.g. operate together with peer devices, or get SW updates over the internet, etc.

This could also mean it can autonomously discover a domain registrar and use it, e.g. for renewing its CA certs, or for renewing its own LDevID cert by doing a 'reenroll' EST request. 

I think we would need a section to say if that kind of operation is foreseen/allowed.  To me it sounds like a common use case. Once the device is fully integrated into the domain network and that's up and running, it is unnecessary to send a person with a tool to update certificates!

**Comment by EskoDijk** [comment]
If a device supports both BRSKI and BRSKI-PRM, it may not be yet clear if/how these procedures can be mixed and matched. For example, supporting both doesn't imply that a PRM-enrolled device can later use BRSKI-regular to renew a LDevID cert. We could mention it as example but it seems a bit outside the scope of this document - e.g. there may be hidden security implications.

There's also the case of supporting only BRSKI-PRM, but supporting more generally EST (RFC 7030) for things like updating Domain CA certs, or renewing LDevID cert, at an EST server.   (This EST server may be a BRSKI Registrar, but doesn't have to be. In practice it will likely be.)  This is the case I was wondering about.  We may just refer to RFC 7030 and say this is possible.

**Comment by stfries** [comment]
It really depends on the use case and device capabilities. A device may be bootstrapped using BRSKI-PRM for instance in a cabinet and once the cabinet is installed, it may use EST or others for certificate management. We could provide a statement that if the device can also act as a client, it may act as client for standard certificate management protocols like EST in the final operational environment. If not it can still be triggered using the available endpoints to generate new PER.

**Comment by EskoDijk** [comment]
Ok sounds good to just mention that option. (PER of re-enrollment type is an example)

**Comment by stfries** [comment]
Included the following text into section 3: Once a pledge with such combined functionality has been bootstrapped, it may act as client for enrollment or re-enrollment of further certificates needed, e.g., using the enrollment protocol of choice. 
If it still acts as server, the defined endpoints can be used to trigger a PER for further certificates.
