### ISSUE TITLE
Unclear sentence "The provisionally ... contained (optional feature)." 5.2

### ISSUE THREAD

**Issue by EskoDijk** [anima-wg/anima-brski-prm#32]
> The provisionally accepted LDevID(Reg) EE certificate can be verified after the voucher has been processed by the pledge through a verification of an additional signature of the returned voucher by the registrar if contained (optional feature).

Not sure what was intended here. Better to split into multiple sentences?

1. If the voucher pins the LDevID(Reg) cert: pledge can directly verify that pinned cert == provisionally accepted LDevID(Reg)
2. If the voucher pins a DomainCA cert: pledge can verify that provisionally accepted LDevID(Reg) chains-to DomainCA.

So it seems that the MASA would verify PoP of the private key of registrar, and if that checks out okay, it creates the voucher. Then the pledge can just accept what's in the voucher and doesn't need the additional signature of registrar to verify PoP.
Is the additional signature by the registrar still needed then?

**Comment by mcr** [comment]
Ideally a MASA would not need any adjustments to deal with PRM situation, and would be ignorant of whether PRM or not.

**Comment by EskoDijk** [comment]
@mcr Yes the MASA can be ignorant; it only performs its usual verifications per RFC 8995, which includes validating the signature of the Registrar on the RVR. The latter proves that the Registrar possesses the private key associated to the registrar-certificate. So the MASA already verifies this; which is why the Pledge presumably does not have to repeat such verification - it can trust the MASA is doing that already.

**Comment by stfries** [comment]
The verification is intended for the pledge. As the pledge only gets the registrar certificate in the agent-signed-data from the registrar-agent and in the voucher from the MASA, he has never verified that the registrar actually possesses the private key. This is different compared to BRSKI as here it is done during the TLS handshake between pledge and registrar. 

I'm not sure the proposal with the split into two statements resolves this, as in both cases the pledge essentially verifies the 
certificate but not PoP of the private key of the registrar. This is hat were aiming for with the additional signature. But I see were the point is, we need to clearly reflect the PoP part 

Changed the sentence to: 
"The provisionally accepted LDevID(Reg) EE certificate can be verified after the voucher has been processed by the pledge. 
If the returned voucher includes an additional signature by the registrar, the pledge can also verify that the registrar possesses the corresponding private key. "

Does it make it clearer?

**Comment by stfries** [comment]
We intended it for two purposes, one is the PoP the other one is an explicit authorization from the registrar. This can also be used to signal that the registrar has verified the voucher, which it does not necessarily do. 
Regarding PoP the intention was to have a similar approach as BRSKI with TLS. Here, the provisional accept is also fully accepted when the voucher is received. The pledge at this point in time has already verified PoP in the course of the TLS handshake.

**Comment by EskoDijk** [comment]
For the first purpose of PoP: if this is important, it should be made mandatory to verify this for the pledge.

For the second purpose of explicit authorization: agree it could be used for this; however if the registrar (with help from the CA) creates an LDevID cert for the device this is already sufficient proof it seems that the registrar has accepted the voucher. (If it needs to verify the voucher first, it would have done so already before creating an LDevID cert right.)  So I'm wondering if there is really a need for the Registrar's signing of the voucher in this case.

If we leave it as optional mechanism, there should be a way for Pledge to indicate to registrar that it needs the additional signature.  (And then it would refuse to proceed with the bootstrap/enrollment if the voucher was not signed this way.)

**Comment by stfries** [comment]
Included signature of registrar as MUST and aligned the processing. Intention is to prove PoP  to the pledge.
