### ISSUE TITLE
Is the size of typical data objects small enough for use with BLE/NFC?

### ISSUE THREAD

**Issue by EskoDijk** [anima-wg/anima-brski-prm#33]
Here just a placeholder for discussing if the data objects are small enough to enable operation with BLE, or NFC bi-directional communication mode (for NFC I read it may be 106 kbit/s link).

With typical data size, how long do these operations take?
1. agent reads data from pledge
2. agent provides voucher/cert to pledge

And is this still in a usable target? (If not, anything we need to do to make it smaller?)

**Comment by stfries** [comment]
Examples have been update in the last sub,mission with messages sizes for all examples

**Comment by stfries** [comment]
Annex of the last version submitted contains examples, including size information
