### ISSUE TITLE
Unify notation of [ brackets ] for sequence diagram figures

### ISSUE THREAD

**Issue by EskoDijk** [anima-wg/anima-brski-prm#34]
Most figures use the [ square brackets ] notation for some action performed by an actor/device at that point in time. This is good, I think.

However fig 3 also uses the same notation to denote "section headers" i.e. a name for some of the following steps to explain what happens. This is also good to have but would need another notation!  Like  { curly brackets } or /* C comment style */ or so.

Example:

```
/* provide pledge-voucher-request to infrastructure */
        |              |<------ TLS ----->|              |            |
        |              |          [Reg-Agt authenticated |            |
        |              |           and authorized?]      |            |
```

**Comment by stfries** [comment]
Included using C comment style for better distinction
