### ISSUE TITLE
MASA requires domain CA cert? 5.5.1 / 5.5.2

### ISSUE THREAD

**Issue by EskoDijk** [anima-wg/anima-brski-prm#36]
In 5.5.1:
> MASA: possesses own credentials (voucher signing key, TLS server certificate) as well as IDevID CA certificate of pledge vendor / manufacturer and site-specific LDevID CA certificate.

First comment: for 5.5.1 scope, only pledge and registrar-agent interact. So there should be no conditions at all on registrar and MASA!
Second comment: we should maybe call it domain CA, not LDevID CA ? LDevID CA is not defined by 802.1AR nor by BRSKI.

Then for 5.5.2, comment on the same requirement: 
Per BRSKI, the Domain CA does not need to be known in advance in all cases. Some MASAs may require this, other may not if they use Trust On First Use (TOFU) for the Domain CA for a new pledge.
Should we be more generic here to allow these TOFU MASAs?

**Comment by stfries** [comment]
Regarding the first comment for 5.5.1: will remove the text, as it does not belong here. 

Regarding the domain CA certificate I would propose the following change:

MASA: possesses it's own vendor/manufacturer credentials (voucher signing key, TLS server certificate) related to pledges IDevID and MAY possess the site-specific domain CA certificate. The latter is necessary when issuing proximity or agent-proximity assertions.

Would this clarify the point?

**Comment by EskoDijk** [comment]
Not clear to met yet - suppose the MASA does not possess the site-specific domain CA certificate, as a precondition. But during the BRSKI process it will automatically get this domain CA cert because it is in the RVR. Then it can still issue a proximity assertion, or an agent-proximity assertion.  

Now that's my understanding but that seems to conflict with the proposed change? (Depending on interpretation of the sentence - only in one interpretation)

**Comment by stfries** [comment]
You're right, it does not related to proximity/agent-proximity. 
 Proposal update to:

MASA: possesses it's own vendor/manufacturer credentials (voucher signing key, TLS server certificate) related to pledges IDevID and MAY possess the site-specific domain CA certificate. The latter is necessary to ensure that the MASA is able to verify the RVR. How the MASA will get the domain CA certificate is out of scope of this document.

Does it make it clearer?

**Comment by EskoDijk** [comment]
Ok; thinking that 'verify the RVR' is more like 'verify that the domain of the Registrar is authorized to enroll the pledge'.
The RVR will be verified in any case, even if the Domain CA isn't on some trust list of MASA.
It could still issue a proximity assertion for a domain that's fully unknown a priori.

And what's still in scope of the document is that the MASA gets the domain CA certificate included in the RVR. Maybe I could think here of some improved wording.

**Comment by stfries** [comment]
Included the text but left the issue open in case you come up with improved wording

**Comment by EskoDijk** [comment]
@stfries Here a proposal for new text
OLD:
  The latter is necessary to ensure that the MASA is able to verify the RVR. 
  How the MASA will get the domain CA certificate is out of scope of this document.

NEW:
  The latter is only a necessary precondition if the MASA needs to verify that the domain of the Registrar is a-priori authorized to enroll a particular pledge, or a particular type of pledge. In such case, how the MASA will obtain the domain CA certificate is out of scope of this document. In other cases, a MASA may allow the pledge to enroll into an anonymous and/or yet-unknown domain and then the a-priori possession of the domain CA certificate is not needed.

**Comment by stfries** [comment]
Took the proposed text into the draft. Issue may be closed.

**Comment by stfries** [comment]
@EskoDijk: Addressed and could be closed.
