### ISSUE TITLE
Somewhat conflicting requirements on Agent possessing the Pledge serial number

### ISSUE THREAD

**Issue by EskoDijk** [anima-wg/anima-brski-prm#38]
In 5.5.1:

>      In addition, the registrar-agent MAY be configured with the product-
>       serial-number(s) of the pledge(s) to be bootstrapped.

This kind of suggests that an Agent may also not know the serial number. But in creating the agent-signed-data, this number is required later on.

Could we clarify perhaps the Agent MUST know the serial-number; e.g. in one of these ways:

1. configured (as in quoted text above)
2. discovered (in "standard" way using mDNS / DNS-SD first part of service instance name)
3. discovered (in vendor-specific way e.g. RF beacons)
3. other (in vendor-specific way, e.g. scan QR code of packaging) - maybe that's the same as category 1 from the Agent point of view.

**Comment by EskoDijk** [comment]
Additional Note: figure 4 doesn't show the part where the Agent discovers the serial number of the Pledge. This was adding to the confusion.  Maybe figure 4 can stay as is; this is just to clarify that at the start of Fig 4 the Agent MUST know the serial-number. So some small link is missing to get the complete picture.

**Comment by stfries** [comment]
I reopened #38 as the initial point if the registrar-agent MUST know the serial number is not solved by the QR code reference. 
As the registrar-agent needs to know, which pledges he is bootstrapping, he needs the list of serial numbers in advance to be able to construct the agent signed data.  Text proposed will be included into the pre-conditions described in section 5.5.1,

In addition, the registrar-agent MUST know the product-serial-number(s) of the pledge(s) to be bootstrapped. 
The registrar-agent MAY be provided with the product-serial-number in different ways:
  * configured, e.g., as a list of pledges to be bootstrapped via QR code scanning
  * discovered by using standard approaches like mDNS as described in 5.4.2.
  * discovered by using a vendor specific approach, e.g., RF beacons
