### ISSUE TITLE
Pledge response HTTP 406 is not the appropriate code, other codes missing?

### ISSUE THREAD

**Issue by EskoDijk** [anima-wg/anima-brski-prm#39]
Section 5.5.1 mentions the Pledge responds 406 when it cannot produce the enrollment request or voucher request.

This seems inappropriate, see https://datatracker.ietf.org/doc/html/rfc7231#section-6.5.6 and also https://datatracker.ietf.org/doc/html/rfc8995#section-5.6 for use of 406 by MASA.
The use of 406 is thus for the case that the Pledge receives another media type than "application/json".

E.g. responses that would be applicable are:
* 400 Bad Request - if there's some error in the format of the request, e.g. missing field, wrong data types, etc. Or it's not valid JSON even though the media type says application/json.
* 403 Forbidden - see https://datatracker.ietf.org/doc/html/rfc8995#section-5.6 for example, or https://datatracker.ietf.org/doc/html/rfc7231#section-6.5.3 . 
    *  For example if the Pledge performs some initial verification as described in 5.5.1 below figure 5 and finds that the Registrar cert is actually not from a Registrar (missing "RA" flag). Or it's a chain which doesn't correctly validate.

It would be useful to include possible error cases on the Pledge side and what it should do then (e.g. respond 4xx errors as in the examples above).

**Comment by stfries** [comment]
okay, good point. Included the following: 
**For PVR**
If the pledge is unable to construct the PVR it SHOULD respond with a HTTP error code to the registrar-agent to indicate that it is not able to create the PVR.
Error codes MAY be used:
* 400: if the pledge detected an error in the format of the request, e.g.. missing field, wrong data types, etc. or it's not valid JSON even though the PVR media type was set to `application/json`.
* 403: if the pledge detected that parameter from the trigger message to create the PVR were not valid, e.g., the LDevID (Reg) certificate.
* 
**For the PER** I include a little deviating text, as the trigger may be empty:
If the pledge is unable to construct the PER it SHOULD respond with a HTTP error code to the registrar-agent to indicate that it is not able to create the PER.
Error codes MAY be used:
* 400: if the pledge detected an error in the format of the request or it's not valid JSON even though the PER media type was set to `application/json`.
* 403: if the pledge detected that parameter (if provided) from the trigger message to create the PER were not valid.

could be closed?

**Comment by stfries** [comment]
Changes included in section 5.5.1 below Figure 6 and Figure 8. 

@EskoDijk please check and provide your feedback.

**Comment by EskoDijk** [comment]
I'd like to provide an additional pass on the text with the following:
* terminology: "HTTP status code" is the right name
* 415 should be used if an unsupported or unknown media type is being pushed into a resource
* (406 only if the requested media type as listed in an Accep theader is not acceptable)
* Add names of HTTP error codes for readability (hope that's ok - saves a lot of lookups!)
* fix typos

I'll create a PR which makes the reviewing of changes easier.

**Comment by stfries** [comment]
Merged the proposed changes and closing issue
