### ISSUE TITLE
Can the Pledge always know the time?

### ISSUE THREAD

**Issue by EskoDijk** [anima-wg/anima-brski-prm#43]
In 5.5.1, inclusion of created-on is mandatory for the PVR. This seems limiting, the pledge may not know the time. Or does it get time from the Registrar-agent?

It could also be ok to just include the nonce only and use this for the Pledge (and also MASA - if it sees the same nonce twice or more it knows something's wrong) to determine some level of  freshness.

**Comment by stfries** [comment]
Pledge may have an own time, it can also take the time out of the agent-signed-data, if it has no own time. Will add this to the description.

**Comment by EskoDijk** [comment]
Ok, so if time is always present in the agent-signed-data, then the Pledge could always use this if it doesn't have its own clock. So if we make this clear then we can have mandatory created-on field.
