### ISSUE TITLE
Figure 8 confusing and not valid JSON

### ISSUE THREAD

**Issue by EskoDijk** [anima-wg/anima-brski-prm#44]
Figure 8 is presented as an example, but seems not further defined in formal terms. (E.g. initial enrollment vs re-enrollment)
* No formal format definition - should we say this is left for later specs?
* spelling error "intial"
* not valid JSON
* How would a Pledge decide to choose re-enrollment here?
* Why not just leave empty for initial enrollment?
* Can there be vendor-specific data included in that JSON? If yes, wouldn't that conflict with a future definition? If no, shouldn't we have such a feature?  Can we define a JSON structure of 2 parts - one vendor-specific data only, and one to be standardized in the future?

**Comment by stfries** [comment]
We changed the text to the following to define the scope of "enroll-type". 
: 
Note that using HTTP POST allows for an empty body, but also to provide additional data, like CSR attributes or information about the enroll type: "enroll-generic-cert" or "reenroll-generic-cert". 
The "enroll-generic-cert" case is shown in {{raer}}.

~~~~
{
  "enroll-type" = "enroll-generic-cert"
}

enroll and re-enroll are both related to the generic LDevID certificate of the pledge as this is the scope of BRSKI-PRM. 

Does this make it clearer?

**Comment by EskoDijk** [comment]
Ok; still to change the '=' to a ':' character. And we could say that empty POST body indicates the exact payload as seen in {{raer}}.

**Comment by stfries** [comment]
I included the ":". 

I changed the text below the figure to 

In the following the enrollment is described as initial enrollment with an empty HTTP POST body.

Could be closed

**Comment by siethower** [comment]
Sounds good to me.
