### ISSUE TITLE
Unclear sentence "no trusted timestamp"

### ISSUE THREAD

**Issue by EskoDijk** [anima-wg/anima-brski-prm#45]
> Validity of used signing certificates during
>       bootstrapping is necessary as no trusted timestamp is available,
>       see also [Section 9.3](https://datatracker.ietf.org/doc/html/draft-ietf-anima-brski-prm#section-9.3).

This is not clear; who is missing a trusted timestamp? Section 9.3 doesn't make that clear.

- The Pledge could have a RT clock  (there's a requirement for it to include 'created-on' time)
- The Agent could have a RT clock   (often, this could be better than the Pledge's i.e. more recently synced!)
- Registrar supposedly always has a clock (e.g. local or time server, etc.)
- Same for MASA

**Comment by stfries** [comment]
The point was that the timestamp has to be in the validity boundaries of the LDevID(RegAgt) certificate to avoid, that a registrar agent may generate agent-signed-data for arbitrary pledges to be bootstrapped in advanced. That was the attack described in 9.3.  It is specifically necessary, if the registrar would accept arbitrary pledges from a vendor.

Proposal to change the sentence to: 
Validity of used signing certificates at the time of signing the agent-signed-data is necessary to avoid that a rogue registrar-agent generates agent-signed-data objects to onboard arbitrary pledges at a later point in time. 

Would that make it clearer?

**Comment by EskoDijk** [comment]
Sounds clearer indeed, I'll recheck when sending my PR for 'nits' and see if anything can be clarified still.

**Comment by stfries** [comment]
Okay, I took the proposal and left the issue open
