### ISSUE TITLE
Unclear paragraph "If the agent-sign-cert is not included, ... "

### ISSUE THREAD

**Issue by EskoDijk** [anima-wg/anima-brski-prm#46]
> The MASA uses this information for verification of the agent is in
>    proximity to the registrar to state the corresponding assertion
>    "agent-proximity".  If the agent-sign-cert is not included in the
>    registrar-voucher-request (RVR), it is also contained in the "prior-
>    signed-voucher-request" field carrying the pledge-voucher-request
>    PVR.

of the agent -> that the agent?

Last sentence is unclear to me. Is it like:

>    If the agent-sign-cert is not included in the RVR
>    directly, the MASA can obtain this data indirectly by first extracting the PVR from the "prior-
>    signed-voucher-request" field, and then extracting the data from the "agent-sign-cert" field of this PVR.

**Comment by stfries** [comment]
- corrected to "that the registrar-agent..."
- Last sentence was misleading indeed. Changed to "Note that the agent-sign-cert may also be contained in the "prior-signed-voucher-request" carrying the PVR if the pledge included it." The agent-signed-cert is contained in the RVR in any case.

**Comment by EskoDijk** [comment]
Ok
