### ISSUE TITLE
Requirement "same domain CA as LDevID(Reg)" -> MUST?

### ISSUE THREAD

**Issue by EskoDijk** [anima-wg/anima-brski-prm#47]
> It can be verified by
>       the MASA that it was issued by the same domain CA as the
>       LDevID(Reg) EE certificate.

That should be a MUST ?   I.e. the RegAgt MUST be from the same domain as the Registrar.

**Comment by stfries** [comment]
Yes. Will adopt the text to: 
It MUST be verified by the MASA that it can be verified to the same domain CA as the LDevID(Reg) certificate.

The reason for this formulation is that the RegAgt may get its certificate from a subCA of the domain CA.

**Comment by EskoDijk** [comment]
Ok
