### ISSUE TITLE
What if Pledge requires Registrar's additional signature

### ISSUE THREAD

**Issue by EskoDijk** [anima-wg/anima-brski-prm#49]
> The registrar MAY add an additional signature to the
>    voucher-response object, by signing it using its registrar
>    credentials (LDevID(Reg)). 

What if the Pledge requires it, and the Registrar doesn't add it?
To remain compatible with this spec, a Pledge MUST accept also a voucher that's not signed in this way - would reduce security maybe?  And to avoid potential trouble a Registrar would just opt to always exclude this additional signature, increasing its success probability.

**Comment by stfries** [comment]
Good point. Proposal to make it a MUST. This also addresses #32

**Comment by stfries** [comment]
After discussion inclusion as MUST. Also adopted the pledge processing as mandatory accordingly.
