### ISSUE TITLE
Registrar sends both original and enhanced PKCS#10 request?

### ISSUE THREAD

**Issue by EskoDijk** [anima-wg/anima-brski-prm#50]
> The domain registrar may either enhance the PKCS#10 request or
>       generate a structure containing the attributes to be included by
>       the CA into the requested LDevID EE certificate and sends both
>       (the original PKCS#10 request and the enhancements) to the domain
>       CA. 

"sends both" is not fully clear. I can imagine these scenarios:
1. RA authenticates Pledge; verifies the IDevID-based signature as well as the PKCS#10 signature which together establishes PoP of the LDevID private key by the Pledge; then RA adapts/amends the CSR; and sends it to CA.  CA does not check PKCS#10 signature because that is RA's job. CA creates LDevID cert and it MAY still adapt/amend some specific fields where needed but most of that was already done by RA.
2. RA authenticates Pledge; verifies the IDevID-based signature as well as the PKCS#10 signature which together establishes PoP of the LDevID private key by the Pledge; then RA forwards the CSR as is to CA.  CA checks PKCS#10 signature. CA then amends/modifies the fields of the LDevID cert to make it suitable for the domain (e.g. adapt naming etc, add fields), signs the LDevID cert and sends it back to RA.
3. RA authenticates Pledge; verifies the IDevID-based signature as well as the PKCS#10 signature which together establishes PoP of the LDevID private key by the Pledge; then RA creates an adapted/amended version of the CSR; and sends both original and amended versions of the CSR to the CA.  CA checks PKCS#10 signature on the original version only. CA then creates an LDevID cert based on the amended CSR fields, signs it, and sends it back to RA.  The CA MAY optionally still amend/modify some fields as needed (but most of that would have already been done by RA who knows the details of what needs to go into the domain certificate and what the role/purpose of the new device will be.)

Should all of these be covered by the text? Or are some of the scenarios not realistic?
Personally I was considering the CA always as just the entity that "rubberstamps the papers" i.e. will enroll whoever the RAs ask it to enroll into the domain, with any certificate fields as requested by the RA. But RFC 5280 isn't defining in detail how the tasks are distributed between RA/CA. Authentication of the requester (Pledge) and deciding if it can join is clearly an RA task.

**Comment by stfries** [comment]
Proposal to verify the handling in EST first. In general all three options should work. In option 3 the RA would most likely not create a CSR, as it does not possess the private key of the pledge. I have to double check, how additional attributes can be provided by an RA.

**Comment by EskoDijk** [comment]
Ok for me!
