### ISSUE TITLE
Definition of HTTP status codes for /requestenroll

### ISSUE THREAD

**Issue by EskoDijk** [anima-wg/anima-brski-prm#51]
> If validation of the wrapping signature fails, the registrar SHOULD
>    respond with the HTTP 404 error code.  The HTTP 406 error code SHOULD
>    be used, if the pledge-enrollment-request (PER) is in an unknown
>    format.

Because we define a new (BRSKI-PRM) resource here we can't automatically rely on the HTTP status codes defined for EST in RFC 7030. So maybe a bit more detail is required, e.g. EST mentions 200 for the success case. And also 202; do we support 202 in the same way?  Also it mentions 4xx/5xx in general as the general catch-all error case which we could also do for remaining status codes.

>    A situation that could be resolved with administrative action (such
>    as adding a vendor/manufacturer IDevID CA as trusted party) MAY be
>    responded with the HTTP 403 error code.

I think the above part isn't needed here. Reason: at this point the registrar already accepted the voucher-request of Pledge, and MASA provided the voucher, and registrar provided the voucher to the agent.
If the IDevID CA would not be properly installed in registrar, then this voucher process would have already failed.

403 could instead be used for cases where the signature validation fails e.g. as defined in 5.6 of RFC 8995 for the registrar's voucher response that is derived from the MASA voucher response. That makes more sense than the 404 defined in 5.3 of RFC 8995 for the registrar's early error response. But anyhow, we can choose either way.

**Comment by stfries** [comment]
In the success case I would propose to use 200 only as the registrar-agent would expect the response directly.

In the failure case we will use 403 as suggested.
