### ISSUE TITLE
Can revocation state be validated in step 4 (5.5.3)?

### ISSUE THREAD

**Issue by EskoDijk** [anima-wg/anima-brski-prm#52]
> 4.  Validate the registrar certificate received in the agent-
>        provided-proximity-registrar-cert in the voucher request
>        successfully, including revocation state of the certificate,
>        validity, and authorization to bootstrap the particular pledge.

Main comment: the pledge can't validate revocation state of the registrar, because it's not part of the domain yet at this point. In almost all cases there's not even a network connection the pledge could use. And even if it would have network (e.g. built-in cellular?) then it would probably not be able to reach the revocation server(s) of the closed/firewalled domain .

Minor comment on "received in the agent-provided-proximity-registrar-cert in the voucher request" -> a bit unclear. It sounds as if the Pledge received its own PVR. So better is e.g. :

"previously received from the registrar agent in the pledge-voucher-request trigger request (in the field "agent-provided-proximity-registrar-cert")"

**Comment by EskoDijk** [comment]
Similar comment on Pledge checking revocation state for its own LDevID cert:

> Upon reception, the pledge SHALL verify the received LDevID EE
>    certificate.  The pledge MAY omit the revocation check as the EE
>    LDevID certificate was freshly issued..  

At this point, the pledge is unable to do the revocation check.

**Comment by stfries** [comment]
good point, I removed the revocation checks in both cases. I also took over the clarification regarding the trigger message, to not confuse the reader 

Could be closed

**Comment by EskoDijk** [comment]
Ok
