### ISSUE TITLE
MASA sends audit log without any request? (Fig 17)

### ISSUE THREAD

**Issue by EskoDijk** [anima-wg/anima-brski-prm#54]
MASA should be requested in Fig 17, to send the audit log.

Likely, this can also happen after the agent sent the enroll-status.

**Comment by stfries** [comment]
Enhanced the figure with the request fro the audit log. It was included in the overall call flow for BRSKI-PRM, but left out for no reason in this figure.

**Comment by EskoDijk** [comment]
See also my comment on https://github.com/anima-wg/anima-brski-prm/issues/42 about potentially doing the audit-log request twice and checking twice. That would be a possibillity, in my view.
