### ISSUE TITLE
Registrar providing 404 error after successful processing is bad

### ISSUE THREAD

**Issue by EskoDijk** [anima-wg/anima-brski-prm#55]
Some instances of:

> According to [RFC8995] section X, the registrar SHOULD respond with
>    an HTTP 200 but MAY simply fail with an HTTP 404 error.
> 

This could be understandable if sent directly to a Pledge. Because the pledge doesn't do anything with the response code: the reporting has been done.

For the registrar-agent case that's hugely different! It needs to know that the reports it made are successfully received, or not, and which ones were successful.  So its 200 for a success case ; and other 4xx/5xx codes may be used as defined by the HTTP standard.

We could think about using 403 in case the signature validation on the object fails ; but not sure if the agent can do anything with that information.

**Comment by stfries** [comment]
changed to : According to {{RFC8995}} section 5.9.4, the registrar SHOULD respond with an HTTP 200 in the success case or fail with HTTP 4xx/5xx codes as defined by the HTTP standard.

**Comment by EskoDijk** [comment]
Yes, that seems sufficient.
