### ISSUE TITLE
Section 9.1 exhaustion attack - expand text

### ISSUE THREAD

**Issue by EskoDijk** [anima-wg/anima-brski-prm#59]
9.1 looks like a placeholder - text to be expanded.

**Comment by stfries** [comment]
Text expanded in security considerations and privacy considerations

May be closed after review or addition of further security/privacy considerations.

**Comment by EskoDijk** [comment]
Ok, there are now "TODO" placeholders in the text on Github to fill. Leaving this issue open for that.

**Comment by stfries** [comment]
Text has been expanded. TODO was merely to think about further threats.

**Comment by stfries** [comment]
Has been addressed with the latest update
