### ISSUE TITLE
References: normative vs informative

### ISSUE THREAD

**Issue by EskoDijk** [anima-wg/anima-brski-prm#60]
Normative refs that should be informative:
* RFC 6241 should be informative (not normatively needed to implement)
* RFC 8407 (same)

Informative refs that should be normative:
* RFC 2986 - without PKCS#10, you can't implement the protocol.
* RFC 5280 - without this specific (PKIX) certificate structure, you can't interoperably implement the protocol.

**Comment by stfries** [comment]
completely agree, done
