### ISSUE TITLE
Two terms used: "LDevID certificate" and "LDevID EE Certificate"

### ISSUE THREAD

**Issue by EskoDijk** [anima-wg/anima-brski-prm#62]
Preferably, only the official term "LDevID certificate" should be used - unless a good reason to deviate in particular cases.

(Better, where needed we explain "LDevID certificate, which is an EE certificate ... " or so)

**Comment by stfries** [comment]
There should be a single term, right. LDevID EE certificate was used to underline it is an entity certificate and not an intermediate CA certificate. We also used LDevID (CA) certificate. I understood from another comment, you prefer to use domain CA certificate.

My understanding of LDevID was the relation to a device (independent of its function), not necessarily to the end entity.

**Comment by EskoDijk** [comment]
See 802.1AR for the terminology; an LDevID is a DevID; and a DevID certificate is mentioned to be an end entity in 3.7. But it's rather implicit. If needed we can just clarify this in terminology.

Also Section 6 text of 802.1AR-2018 strongly suggests that CAs are not DevIDs. They're called "CA" in that standard. In BRSKI, the term "Domain CA" was used which is more clear in our context.

So I do think that considering CAs to be DevIDs potentially would be confusing, and probably incorrect.

**Comment by stfries** [comment]
Okay, understood. Than I would propose to go ahead and make the change to LDevID certificate and add an explanation also in the terminology section regarding relation to EE.
