### ISSUE TITLE
Freshness of pledge enrollment-request (PER)

### ISSUE THREAD

**Issue by siethower** [anima-wg/anima-brski-prm#63]
Currently we do not have any "created-on" or "timestamp" information in the PER (see: draft-ietf-anima-brski-prm.html#figure-9).  
- freshness of PER should be reconsider  
- may be also in combination proofing the involvement of registrar-agent, e.g. by using "agent-signed-data" also in PER (see: draft-ietf-anima-brski-prm.html#figure-9) and the trigger for PER (draft-ietf-anima-brski-prm.html#figure-8)  
- revisit handling and content of PVR and PER, should be in similar fashion

**Comment by stfries** [comment]
Two variants to be distinguished: 
- nonced-voucher: as proposed, created-on inclusion into PER seems to be sufficient, as the timeliness/freshness can be ensured.
- nonceless-voucher: Assumption trigger/PVR not used
  - if we omit the trigger and the PVR, the registrar has no information, that a pledge will be bootstrapped, prior to the PER. Also, the registrar does not know, which registrar-agent performs the bootstrapping. 
  - This would require to always perform the trigger/PVR to let the domain registrar know about the bootstrapping. In addition, BRSKI-PRM requires the voucher to be also signed by the registrar. 

Proposal:
- always perform trigger/PVR. This provides agent-signed data to registrar and allows for authorized bootstrapping.
- include created-on into PER, require created-on is after created-on in agent-signed-data from PVR. This supports freshness of the PER. The registrar can verify that the pledge is allowed to request a certificate based on the prior PVR.
- agent-signed-data in PER not seen as necessary. Inclusion of created-on avoids bigger PER in the constraint case.

**Comment by EskoDijk** [comment]
@stfries  

> if we omit the trigger and the PVR, the registrar has no information, that a pledge will be bootstrapped, prior to the PER. 
Most likely a bunch of Vouchers was already obtained (OOB) and loaded (OOB) into the Registrar, prior to starting the process with the Agents. So the devices to on-board can be known in advance, in this way.

I agree the proposal solves some issues and it nicely keeps the message flow and formats the same whether using nonceless vouchers or nonced vouchers.  That is also a property of BRSKI-classic: the Registrar would first receive a proper PVR from the Pledge before handing out the (precreated) nonceless Voucher.

This will then also solve the freshness issue I believe.  The Registrar can check:
* created-on of PER needs to be >= created-on of the PVR. 
* created-on of PVR needs to be >= created-on of "trigger for PVR" i.e. the agent's time information
* created-on of PER needs to be >= created-on of Voucher

One thing to keep in mind is that the PVR may contain a nonce, while the Voucher will then not have a nonce in this scenario. But that's the same as with BRSKI-classic  -  It's up to the vendor's policy for the device to accept a nonceless Voucher yes or no.

**Comment by stfries** [comment]
Regarding the nonceless voucher, we already have a statement that it depends on the vendor, if the pledge accepts it or not:
"A nonceless voucher may be accepted as in {{RFC8995}} and may be allowed by a manufactures pledge implementation."

**Comment by siethower** [comment]
Thanks can be closed, after we found the solution with  "created-on" and "crit" parameter according to RFC 7515

**Comment by stfries** [comment]
okay, closing
