### ISSUE TITLE
CABforum comments may be superfluous

### ISSUE THREAD

**Issue by mcr** [anima-wg/anima-brski-prm#65]
```
Especially the CA/Browser {{CABF}} forum increases the security requirements in the certificate issuance procedures for publicly trusted certificates.
```

CABForum doesn't really say that much about this, and do you expect to go through LetsEncrypt with acme-brski-integrations?
I propose removing this sentence.

**Comment by stfries** [comment]
It was intended as an example but we do not really need it here. Removing the sentence does not harm.
Will do this in the next commit.

**Comment by stfries** [comment]
Removed in latest update
