### ISSUE TITLE
shorten the pledge end points

### ISSUE THREAD

**Issue by mcr** [anima-wg/anima-brski-prm#67]
Figure 2 defines the new end-points on the pledge.
Since COAP (over IP, or over BTLE) is anticipated, should we just start with shorter path values?
/pvr rather than /pledge-voucher-request ?, etc.?

**Comment by siethower** [comment]
The idea is to start with short names/abbreviations directly to prepare for constraint environments (in future).
Let's have a look and find some good naming.

**Comment by stfries** [comment]
Incorporated as proposed
