### ISSUE TITLE
is WiFi encrypted?

### ISSUE THREAD

**Issue by mcr** [anima-wg/anima-brski-prm#69]
Does the pledge run a softAP?
Is the network involved encrypted?
We should deal with security issues in 5.4.2: we will get called out on this.
I think it's fine that we have an unencrypted ad-hoc network, but we should say this explicitely.

````
For WiFi networks, connectivity can be provided by using a pre-agreed SSID for bootstrapping.
The same approach can be used by 6LoWPAN/mesh using a pre-agreed PAN ID.
How to gain network connectivity is out of scope of this document.
````

**Comment by stfries** [comment]
The proposed text as such is fine, but as stated, it is out of scope of the document.
