### ISSUE TITLE
why is certificate optional in section 5.5?

### ISSUE THREAD

**Issue by mcr** [anima-wg/anima-brski-prm#70]
````
Optionally the registrar-agent may provide its LDevID(RegAgt) certificate (and optionally also the issuing CA certificate) to the pledge to be used in the "agent-sign-cert" component of the PVR. 
````
Related to 8608f81 .
I'm not sure we should have an optional part here. 
I don't think it saves much bandwidth, if we can do without it, then why have it at all?
I suspect that I need a picture to understand this.

**Comment by stfries** [comment]
Removed agent-sign-cert from the PVR to ease the handling. Is kept in the RVR to allow the verification on the MASA to issue an agent-proximity assertion.
