### ISSUE TITLE
section 5.5 is foreshadowed/repeated

### ISSUE THREAD

**Issue by mcr** [anima-wg/anima-brski-prm#72]
Section 5.5 goes through all the steps of the interaction between components.
But it seems that section prior to 5.5, and all the way back to the introduction have already given most of the details.
The document seems too long as a result and feels repetitive.  I think that the answer is to say less early on, and reference the 5.5 sections.  Maybe 5.5 is important enough to be an entire section on its own?

**Comment by stfries** [comment]
Restructured the document to make section 5.5 no section 6. Will go over the text to remove repetitive text and use references instead.

**Comment by stfries** [comment]
With the last commit some shortenings in the preceding sections have been made. Also, section 5.5 is now section 6 to have a better structure of the draft. If you could double check and potentially propose further changes if necessary would be great.

**Comment by siethower** [comment]
some improvements: https://github.com/anima-wg/anima-brski-prm/commit/e3f4a42f11b8038bad9ebe515580718a7b277266

**Comment by siethower** [comment]
Restructuring of chapter 6, with following result:  
6.  Bootstrapping Data Objects and Corresponding Exchanges
6.1.  Request Objects Acquisition by Registrar-Agent from Pledge
6.1.1.  Pledge-Voucher-Request (PVR) - Trigger
6.1.2.  Pledge-Voucher-Request (PVR) - Response
6.1.3.  Pledge-Enrollment-Request (PER) - Trigger
6.1.4.  Pledge-Enrollment-Request (PER) - Response
6.2.  Request Object Handling initiated by the Registrar-Agent to Registrar
6.2.1.  Connection Establishment (Registrar-Agent to Registrar)
6.2.2.  Pledge-Voucher-Request (RVR) Processing by Registrar
6.2.3.  Registrar-Voucher-Request (RVR) Processing (Registrar to MASA)
6.2.4.  Voucher Issuance by MASA
6.2.5.  MASA issued Voucher Processing by Registrar
6.2.6.  Pledge-Enrollment-Request (PER) Processing (Registrar-Agent to Registrar)
6.2.7.  Request Wrapped-CA-certificate(s) (Registrar-Agent to Registrar)
6.3.  Response Object Supply by Registrar-Agent to Pledge
6.3.1.  Pledge: Voucher Response Processing
6.3.2.  Pledge: Voucher Status Telemetry
6.3.3.  Pledge: Wrapped-CA-Certificate(s) Processing
6.3.4.  Pledge: Enrollment Response Processing
6.3.5.  Pledge: Enrollment Status Telemetry
6.3.6.  Telemetry Voucher Status and Enroll Status Handling (Registrar-Agent to Domain Registrar)
6.4.  Request Pledge-Status by Registrar-Agent from Pledge
6.4.1.  Pledge-Status - Trigger (Registrar-Agent to Pledge)
6.4.2.  Pledge-Status - Response (Pledge - Registrar-Agent)

**Comment by siethower** [comment]
Hello @mcr, did some more restructuring and improvements to chapter 6.  
Please check, thanks for your feedback.
