### ISSUE TITLE
pledge-status responses are cumullative right?

### ISSUE THREAD

**Issue by mcr** [anima-wg/anima-brski-prm#73]
I think that enroll-success implies voucher-success, but I don't see this stated in section 5.5.5.
I also think that enroll-error implies voucher-success, but I'm not sure about this.

**Comment by stfries** [comment]
Yes, this is the case. Needs to be stated explicitly:
connection-success implies enroll-success implies voucher-success

**Comment by stfries** [comment]
Explicitly taken over in section 5.5.5
