### ISSUE TITLE
what is the threat for registrar-agent mis-use

### ISSUE THREAD

**Issue by mcr** [anima-wg/anima-brski-prm#74]
section 9.3 _Misuse of Registrar-Agent Credentials_ suggests a mitigation for a mis-behaving registrar-agent.
Specifically, it is suggested that a short LDevID(RegAgt) solves this.  I agree that it could reduce the window during which mis-use could occur, but it is unclear what the mischief that could be caused is.
I suggest that this section be re-written to first explain what a registrar-agent could do (outline the threat), and then we can better evaluate what the mitigations are and how well they work?

**Comment by mcr** [comment]
The section half of section 9.3 suggests a time-stamp based attack, but I'm unclear what the end attack is.
In any case, a new check is suggested in this section, and I'd prefer that this goes into section ... uhm.
It seems that we have no section that explains the new behaviours of the Registrar.  I think we need a new section between 5.4 and 5.5.

**Comment by stfries** [comment]
The attack described addresses the case in which a rogue registrar-agent creates arbitrary agent-signed-data blobs, which could be misused in the future to onboard pledges. Therefore the requirements to have short term certificates as well as the check that the certificate is valid during the bootstrapping process.
The attack is referenced in the text for the agent-signed-data in section 5.5.2

**Comment by stfries** [comment]
Is there more explanatory text needed? The attack is explained in the security considerations and the duties of the registrar are explained in  the object handling of the registrar

**Comment by stfries** [comment]
No further comments received, Text assumed to be sufficient
