### ISSUE TITLE
misuse of mDNS (9.4)

### ISSUE THREAD

**Issue by mcr** [anima-wg/anima-brski-prm#75]
I'm not sure what the security concern with getting the list of all pledges.
Perhaps there is a concern with attacker being able to enumerate all the pledges?

**Comment by stfries** [comment]
The concern was raised in the Design Team. The goal was to avoid a listing of devices by a single request. This would already provide information to an attacker which devices are available in the network (waiting for onboarding).

**Comment by stfries** [comment]
Clarify text in the security consideration section: enumeration is a feature not a bug. Some devices may not answer when serial number is not contained

**Comment by stfries** [comment]
Added a description in the security consideration and also in the discovery section
