### ISSUE TITLE
Registrar Signature on enrollment response object needed?

### ISSUE THREAD

**Issue by stfries** [anima-wg/anima-brski-prm#8]
Currently we provide the pledge's LDevID certificate in the enrollment response object without an additional signature from the registrar. This is fine if only the certificate is provided. An additional signature may be useful:
- if additional data is included by the registrar
- for audit purposes to verify, which registrar has provided the certificate to the pledge. In BRSKI this is ensured by using the already established TLS connection between pledge and registrar. But this is not available in BRSKI-PRM. The TLS connection here ends at the registrar-agent.

Any thoughts?

**Comment by mcr** [comment]
The voucher reply included the Registrar's certificate.  That should show which registrar.
You've mentioned some kind of configuration blob.  Would that be signed?

**Comment by stfries** [comment]
That is the question. The enrollment response as we have currently defined in BRSKI-PRM contains only the LDevID. The message is currently not signed. The question would be is we see a need to provide further values with this message, which need to be provided in an authenticated way. In this case we would need to add a signature.

**Comment by stfries** [comment]
Based on the current state of discussion, the enrollment response provided to the pledge will only contain a single LDevID EE certificate which enables further interactions in the domain. Based on this LDevID further configuration can be performed. Part of the application specific configuration is also the provisioning of further security related parameters, upon the pledge may create further certification requests. This is done outside the scope of the BRSKI-PRM draft but may reuse some of the functionality BRSKI-PRM provides.

Issue can be closed
