### ISSUE TITLE
use of registrar endpoints for responder vs. initiator mode

### ISSUE THREAD

**Issue by stfries** [anima-wg/anima-brski-prm#84]
Toerless WGLC review: 

I would suggest to change the media-type for PRM to:
    application/voucher+prm+ws+json

Addresses situations, in which the format may also be used by standard BRSKI.

The same consideration should be used for any other media type this
document uses where the endpoint could likely be shared between
PRM and non-PRM in the future.

Of course, there are alternatives like introducing PRM specific endpoints.
I really have no good criteria to pick one over the other, a.a.: to
me "/requestvoucher-prm" would be equally fine.

**Comment by stfries** [comment]
The registrar distinguishes between pledge and registrar-agent is based on the utilized *DevID. If an LDevID is used, the request originates from the registrar-agent. It can then verify the content of the PVR including the agent-signed-data.
If an IDevID is used, the request originates from a pledge. Proposal to leave it like this.

**Comment by mcr** [comment]
Based upon discussion about +cose and +cwt and the mediaman WG's document on multiple types, I think that voucher+json is probably better.  What does "ws" stand for above?
I agree with the second comment about how the Registrar knows who is communicating.

**Comment by stfries** [comment]
JWS voucher to be updated/discussed regarding the media type: proposal application/voucher+jws
If changed to be taken over in BRSKI-PRM

**Comment by stfries** [comment]
Can be closed based on discussion June 6, 2023:
- Constraint voucher likely use form factor CBOR-in-COSE_Sign, which is independent from JSON-in-JWS signed
