### ISSUE TITLE
Available information on registrar-agent

### ISSUE THREAD

**Issue by stfries** [anima-wg/anima-brski-prm#87]
Comment from Toerless: 

Section 6.1 currently states as precondition that the registrar-agent possesses the IDevID CA certificate. This may not be necessary.

> Why is this trust into pledges IDevID needed ? If the registrar-agent would
> simply query and
> send any PVR it can find (potentially limited by configured list of serial
> numbers) to the registrar, we wold continue with the fairly failsafe
> registrar-centralized diagnostics. If we do validation of IDevID on
> registrar-agent, then we hav potentially many registrar agents that all
> have to be perfectly configured to operate correctly, and we need to
> invent another new diagnostics channel to recognize in our central
> backend (registrar) any unforeseen failures. Aka: pledges who have a
> different
> trust chain than what the vendor promised the to have (don't ask me about
> how much mess up in certificate management lage vendors can have.
> Especially
> when they go around shopping/integrating companies into product lines...).

**Comment by stfries** [comment]
In general the intention was to enable the registrar-agent to verify the PVR, if it possesses the IDevID CA cert. 
Proposal to change the from
_Registrar-agent: possesses/trusts IDevID CA certificate and has own LDevID(RegAgt) credentials for the registrar domain (site). In addition, the registrar-agent MUST know the product-serial-number(s) of the pledge(s) to be bootstrapped. The registrar-agent MAY be provided with the product-serial-number(s) in different ways:_
to 
_Registrar-agent: MUST possess an own LDevID(RegAgt) credential for the registrar domain (site). It MAY possess/trust the IDevID CA certificate. In this case it could already verify the PVR. In addition, the registrar-agent MUST know the product-serial-number(s) of the pledge(s) to be bootstrapped. The registrar-agent MAY be provided with the product-serial-number(s) in different ways:_

Proposal to include the following statement:
If the registrar-agent posses the IDevID CA certificate it may already verify signed response messages received from the pledge and only forward the objects that he was able to verify successfully.

**Comment by stfries** [comment]
relates to #82 to optionally support TLS between pledge and registrar-agent

**Comment by mcr** [comment]
The Registrar-Agent, like the Registrar, has to have a list of manufacturer trust anchors which are trusted.  This is what allows it/them to verify the IDevID.  RFC8995 section 5.3 https://www.rfc-editor.org/rfc/rfc8995.html#name-registrar-authorization-of- 
https://www.ietf.org/archive/id/draft-richardson-anima-masa-considerations-08.html says some thing about the PKI requirements for the IDevID.

**Comment by stfries** [comment]
Changed section 6.1 accordingly and clarified that the product-serial-number-list SHOULD be provided. This allows the registrar agent to also discover all available pledges for onboarding not just distinct ones.
