### ISSUE TITLE
mDNS and discovery of many nodes

### ISSUE THREAD

**Issue by toerless** [anima-wg/anima-brski-prm#93]
PRM specifically wants to support looking for pledges by Name (serial-number). 

Its fine if this information is available, but i think ecvery deployment need to be able to effectively search for all pledges without knowing their serial-number.

One concern when we discussed this was whether/how this would work reliably.

mDNS, rfc6762 should well support discovery of arbitrary number of pledges if the rules of its section 9. which describes random delay for responses and then restarting timer when another reply was seen etc. pp.

It might be good to add a sentence indicating that any discover mechanism used for PRM needs to be avble to support discovery of large number of pledges, and that the mechanism used by RFC6762 should be a well working way to do so (will re-confirm with mdns WG also).

**Comment by stfries** [comment]
- mDNS is covered in section 5.3.2 also with the possibility to discover pledges available for bootstrapping (without list of serial numbers)
- GRASP will be additionally addressed via issue #79

can be closed

**Comment by stfries** [comment]
Included in section 5.3.2: https://www.ietf.org/archive/id/draft-ietf-anima-brski-prm-09.html#section-5.3.2
