### ISSUE TITLE
"optionally CA certificates." - explanation

### ISSUE THREAD

**Issue by siethower** [anima-wg/anima-brski-prm#95]
Comment from Toerless to section 6.3

> 1968          optionally CA certificates.
>  
> Its nice that you reconfirm "optionally" here, but from the text leading here,
> i have seen no description as to who or how determines whether or not
> the CA certificates will be made available to the plegde. Any explanation
> would be nice (whereever it fits best).

**Comment by stfries** [comment]
Proposal to change in section 6.3
_Registrar-agent: possesses voucher and LDevID certificate and optionally CA certificates._
to
_Registrar-agent: possesses voucher and LDevID certificate and optionally IDevID CA certificate._
Additionally add:
_The IDevID CA certificate is necessary, when the connection between the Registrar-agent and the pledge is established using TLS to enable the registrar-agent to validate the pledges' IDevID certificate during the TLS handshake as described in section 6.1._

Add to section 6.1:
_The distribution of CA certificates to the registrar-agent is out of scope of this document and may be done by a manual configuration._

**Comment by stfries** [comment]
incorporate text as proposed.
