### ISSUE TITLE
misleading: "voucher [RFC8366] and the certificate [RFC5280]."

### ISSUE THREAD

**Issue by siethower** [anima-wg/anima-brski-prm#97]
Comment from Toerless to section 6.3

> 1994       The content of the response objects is defined by the voucher
> 1995       [RFC8366] and the certificate [RFC5280].
 
> I think this sentence is misleading here given how we know from prior text
> in this document, that the format is much more specific, such as JWS+JSON
> voucher and pkcs#7-mime certificate.
 
> If this is meant as a more general excurse into how one could potentially
> use all type of encodings in variations of a PRM which are not specified
> in this document, then thats text for an appendix or something much further below,
> but not here. Aka: delete sentence or make references specific to the actual
> formats specified in this spec.

**Comment by stfries** [comment]
Proposal to delete the sentence
