### ISSUE TITLE
nonceless voucher acceptance

### ISSUE THREAD

**Issue by siethower** [anima-wg/anima-brski-prm#98]
Comment from Toerless to section 6.3

> 2011       A nonceless voucher may be accepted as in [RFC8995] and may be
> 2012       allowed by a manufacture's pledge implementation.
>  
> Can a pledge that knows the voucher will be nonceless not include the
> nonce in the JWS+JSON PVR message ? In that case it would be good to
> mention thi earlier in the document where you specify the none message
> element (e.g.: add (optional)).

**Comment by mcr** [comment]
In general, a nonceless voucher is obtained without interacting with the pledge.
So, the pledge usually doesn't know that will be done.
