### ISSUE TITLE
wrong order or miswritten verification steps?

### ISSUE THREAD

**Issue by siethower** [anima-wg/anima-brski-prm#99]
Comment from Toerless to section 6.3

> 2027       4.  Validate the registrar certificate received in the agent-
> 2028           provided-proximity-registrar-cert in the pledge-voucher-request
> 2029           trigger request (in the field "agent-provided-proximity-
> 2030           registrar-cert").
 
> [major]
 
> I think this is in the wrong order or miswritten. Step 3 can not verify a signature
> from a certificate that was not verified in before, and i do not see that the
> registrar certificate mentioned in step 3 was verified in before. Or is this
> assumed to be the pinned-domain-cert mentioned in step 2, and the text just
> uses different words to make it impossible to match up terms ?
 
> But be that as it may: i really don't know what steps 3 and 4 are good for.
> I think they are not needed, but later when pledge-certificate and CA-certs
> are received will those objects need to be authenticated against the
> signature of the registrar, and that requires to first authenticate the
> registrar certificate against the pinned-domain-cert from step 3.
 
> If 3 and 4 can go, that also means that step 2 is not provisional, but
> would per permanent, unless the pinned domain cert is later superceeded by
> the CA certs.

**Comment by stfries** [comment]
As we have the voucher additionally signed, but have not yet the domain certificate installed, the verification starts in at the inner signature from the MASA. This relates to step 1 and 2, which are the normal behavior, also in cases of plain vanilla BRSKI. 
Step 3 and 4 may be exchanged. They target to ensure that the pledge verifies the proof-of-possession of the corresponding private key of the LDevID(Reg) by the registrar. This step is comparable to the TLS handshake part in BRSKI that ensures the pledge can verify the registrar controls his private key. This is specifically important, if the registrar does not provide further CA certs. If CAcerts are provided, they are provided signature-wrapped by the registrar. In that case step 3 and 4 could also be done at that point in time. But wen wanted to describe the approach covering both cases.

**Comment by stfries** [comment]
Add a statement that steps 3 and 4 essentially resemble the TLS channel in BRSKI as BRSKI-PRM uses message based security.

**Comment by stfries** [comment]
Added: 
_Step3 and step 4 have been introduced in BRSKI-PRM to enable verification of LDevID(Reg) certificate and also the proof-of-possession of the corresponding private key by the registrar, which is done in BRSKI based on the established TLS channel._
